### ISSUE TITLE
Missing dependencies from Maven Central

### ISSUE THREAD

**Issue by jponge** [exoplatform/wikbook#9]
I created a project using the provided Maven archetype. However, `mvn package` fails on some dependencies that cannot be resolved from Maven Central, see:

```
[ERROR] Failed to execute goal org.wikbook:wikbook.maven:0.9.28:transform (default) on project wikbook-test: 
Execution default of goal org.wikbook:wikbook.maven:0.9.28:transform failed: 
Plugin org.wikbook:wikbook.maven:0.9.28 or one of its dependencies could not be resolved:
The following artifacts could not be resolved: org.xwiki.platform:xwiki-core-rendering-syntax-wikimodel:jar:2.3.1,
org.wikimodel:org.wikimodel.wem:jar:2.0.7-20100629, org.xwiki.platform:xwiki-core-component-default:jar:2.3.1:
Could not find artifact org.xwiki.platform:xwiki-core-rendering-syntax-wikimodel:jar:2.3.1 in central
(http://repo.maven.apache.org/maven2) -> [Help 1]
```

You should mention that the XWiki repository needs to be added in the user local Maven settings.

**Comment by vietj** [comment]
I'll check with Vincent, normally such deps should be on Maven Central...

**Comment by vietj** [comment]
BTW why are you using  0 .9.28 ?

more recent version are using xwiki dependencies that are on Maven Central I think ?

**Comment by jponge** [comment]
I just followed what the online documentation says and it is on 0.9.28 :-)

**Comment by vietj** [comment]
what about 0.9.42 :-) ?

**Comment by jponge** [comment]
I'll try that and will let you know ;-)

**Comment by jponge** [comment]
Works just fine with 0.9.42, but you should update your documentation and links.

BTW do you plan to have Markdown support? I'm currently pondering
Wikbook vs Pandoc vs AsciiDoc and I remain quite puzzled about which
way to go. (but we can move that discussion in private if you like)

**Comment by vietj** [comment]
I should update doc indeed.

I would love to support markdown (xwiki does support it). I think the main issue is about Macro, I don't think markdown has concept of Macro and I need to check if xwiki MD integration would support it....

**Comment by vietj** [comment]
I don't know much about Pandoc versus Asciidoc.

I think wikbook main differenctiator is about being able to retrieve source code from maven repository and allow to insert it in .wiki documentation .
